[{"raw":{},"required":["Filename","Size"],"package":"python3-exceptiongroup","source":"python-exceptiongroup","version":"1.1.0-1","section":"universe/python","priority":"optional","architecture":"all","depends":["python3:any"],"breaks":["python3-trio (<< 0.22)"],"installedSize":63,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Backport of PEP 654 (exception groups)","homepage":"https://github.com/agronholm/exceptiongroup/","filename":"pool/universe/p/python-exceptiongroup/python3-exceptiongroup_1.1.0-1_all.deb","size":16328,"md5":"80073267eafaac531f89c9247db91b68","sha1":"1800966efed57c772969eadd8ec6aaaaf773c3cd","sha256":"a20ba44254595095993f7aef4bf7213dc2ac974fce474a83a1cd3aaf38d3df9d","sha512":"43b52ac12b099504426250d8301fe8ff995216ebae4bcd8429bc8030f15fdedb61cdd9bf038d4fae654950e5b71a15eb774362a58ce3a8909a6a765887469b28","descriptionMd5":"c0b3bacd074a82b7b90b912e5c5135a1"}]