[{"raw":{},"required":["Filename","Size"],"package":"python-zope.app.error","source":"zope.app.error","version":"3.5.3-0ubuntu4","section":"universe/zope","priority":"extra","architecture":"all","depends":["python-pkg-resources","python-zope","python-zope.app","python-zope.component","python-zope.error","python-zope.publisher","python-zope.traversing","python2.7","python (>= 2.7.1-0ubuntu2)","python (<< 2.8)"],"suggests":["python-zope.app.testing"],"installedSize":110,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Error reporting utility management UI for Zope3","filename":"pool/universe/z/zope.app.error/python-zope.app.error_3.5.3-0ubuntu4_all.deb","size":9776,"md5":"86f322873dc1d465baf1258c6cab9346","sha1":"99279d74fb2d10d4bfe397be5bea4fe5b3808ffb","sha256":"c6e18003d19f064c61f4ccf252d5aacfbdc87a566b59f5cfa34cb29b0d006a5d","descriptionMd5":"4d46000d42a7d4d3895816cff869ebe1"}]