{"raw":{},"required":["Filename","Size"],"package":"python-zope.exceptions","source":"zope.exceptions","version":"4.0.8-1","section":"universe/python","priority":"extra","architecture":"all","depends":["python-pkg-resources","python-zope.interface","python:any (<< 2.8)","python:any (>= 2.7.5-5~)"],"installedSize":93,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Zope exceptions for Python","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/universe/z/zope.exceptions/python-zope.exceptions_4.0.8-1_all.deb","size":14666,"md5":"fc6f6d897b88e5fe5323b8911e8ae72a","sha1":"7ac3fe65e39c468177392893b86c1d40fd60df74","sha256":"f0973c0451dc35e4d4bf591c8739682d8b155353be4a43386ddfdc1ae1066e2d","descriptionMd5":"fb63650b0843d0f5986f71aa80d2082d"}