{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"4.4-1","section":"universe/zope","priority":"extra","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any"],"installedSize":96,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Zope exceptions for Python 3","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/universe/z/zope.exceptions/python3-zope.exceptions_4.4-1_all.deb","size":15800,"md5":"1a216486a4d723f76557d2a275cec4c4","sha1":"5d6c1f01304bd610a6433afb1778f826ab10f783","sha256":"149cf869caa5d9aea7b87b8d70b3ec958fa7f7f6f828d69a001b3d53910169f9","sha512":"3cd4b90e059943847c29f0f08ab14d7803faf64c4bd0a899726faffbff08b98af4a34a6cda8389f47f254570f6fbcdb6cf3dec4cea3f794b1dc4700f1514ca73","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}