{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"4.3-2","section":"universe/zope","priority":"extra","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any"],"installedSize":94,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Zope exceptions for Python 3","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/universe/z/zope.exceptions/python3-zope.exceptions_4.3-2_all.deb","size":15512,"md5":"61306ab7fef6034a130b9ce2990a1778","sha1":"3ecf48170350aa91f32d903fd26361fac478366a","sha256":"de33ea4fc3c58cb7bf0b60adf9f0a1e03943fb58f7c36411bd83bf8a19a27766","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}