{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-exceptiongroup",
	"source": "python-exceptiongroup",
	"version": "1.2.0-1",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3:any"
	],
	"breaks": [
		"python3-trio (<< 0.22)"
	],
	"installedSize": 72,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "Backport of PEP 654 (exception groups)",
	"homepage": "https://github.com/agronholm/exceptiongroup/",
	"filename": "pool/universe/p/python-exceptiongroup/python3-exceptiongroup_1.2.0-1_all.deb",
	"size": 17560,
	"md5": "6ae0f1129f6c4f2be5c897943de2d4d0",
	"sha1": "dfbf8861b0702daa5096b3aeeb9f4a77bc000d1c",
	"sha256": "485df9038e0fcbf2465d246cc2b37cf23dcf6db2793453ebb2a554ddf76a0acf",
	"sha512": "cdc2c6acd066735d10dc4a19753e1b283b8f19588fc77f30245e51d20150d34c250dbac060c95c038f03301b3406cccdf6811f76a6ef5c2317667874cda0ad62",
	"descriptionMd5": "c0b3bacd074a82b7b90b912e5c5135a1"
}