{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python-pytest-instafail",
	"source": "pytest-instafail",
	"version": "0.1.0-1",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python (>= 2.7.1-0ubuntu2)",
		"python (<< 2.8)",
		"python-pytest"
	],
	"suggests": [
		"python-pytest-instafail-doc"
	],
	"installedSize": 64,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "plugin for py.test that shows failures and errors instantly",
	"homepage": "https://pypi.python.org/pypi/pytest-instafail",
	"filename": "pool/universe/p/pytest-instafail/python-pytest-instafail_0.1.0-1_all.deb",
	"size": 5052,
	"md5": "224260c69d5b62e55a0e554efed75a94",
	"sha1": "4f32b217b6a1a82a9f5bf68a55da499267ed4c92",
	"sha256": "34ca12b29f5cb8ff171f10026ef2d03d95f47a7ee09d942c0f0b593de04fd2ed",
	"descriptionMd5": "53ebd8ccc9d7d40b7984d99c2ff6aeac"
}