{"raw":{},"required":["Filename","Size"],"package":"python3-django-dbconn-retry","source":"python-django-dbconn-retry","version":"0.1.7-1","section":"universe/python","priority":"optional","architecture":"all","depends":["python3-django","python3:any"],"installedSize":37,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"reconnect on a failed database (Python3 version)","homepage":"https://github.com/jdelic/django-dbconn-retry/","filename":"pool/universe/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.7-1_all.deb","size":9136,"md5":"c78da3fbbc1d0e68adc8e965f7eb5700","sha1":"e0a23b4a66f2b65f575afdd7230822a821e498e4","sha256":"f36cecd8e770514e980aa780dec861805ede79f29a6607764af84fa9d0f1f33e","sha512":"1b7224114672810e91547178dd426142deb0ecc4e168ba183d9d82998d80024d51b28591237776f5df87256bd85a3fb771fdac71ce3f3d411a10caf2c3d6551f","descriptionMd5":"e6f9867f49ff9821aa4e414064f0370a"}