{"raw":{},"required":["Filename","Size"],"package":"python3-exceptiongroup","source":"python-exceptiongroup","version":"1.1.2-1","section":"universe/python","priority":"optional","architecture":"all","depends":["python3:any"],"breaks":["python3-trio (<< 0.22)"],"installedSize":65,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Backport of PEP 654 (exception groups)","homepage":"https://github.com/agronholm/exceptiongroup/","filename":"pool/universe/p/python-exceptiongroup/python3-exceptiongroup_1.1.2-1_all.deb","size":16670,"md5":"9374bc8a55faf10638141503c11a4fe6","sha1":"67689766247033c875a9cdb33ee79b6b930ac0ce","sha256":"7e2dd6d99f90b3d9e0b3420a91f0eff1d3c91be5b300a29a6f4437d494821880","sha512":"38dc420c0fc00b7e97be5ddaa08d696a2b53c83bb96232e87656822ad0f6f134d36169380405842156798d4002edbfac2d18c9f5330b4e814b159e79ad475de8","descriptionMd5":"c0b3bacd074a82b7b90b912e5c5135a1"}